apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{MY_APP}}-ingress
  namespace: {{MY_APP}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: okk.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{MY_APP}}-service
            port:
              number: 5000
