name: Connect to Azure AKS with Username and Password

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connect-to-aks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Azure with Username and Password
      run: |
        az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    - name: Set up Azure CLI
      run: az account show

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

    - name: Verify Connection to AKS
      run: |
        kubectl get nodes
        kubectl get deployments --all-namespaces=true
